### ISSUE TITLE
Dynamic filtering data in single tenant applications

### ISSUE THREAD

**Issue by hitaspdotnet** [volosoft/abp#317]
Hi guys, you are wonderful 👍 
I have a idea for **single**/multi tenant applications
We can create new spaces like tenants. I chose the **Space** name for it, because space is closer to my idea. 
This space should be a summary of the tenant and the organization unit. 
Each space can have unique user/role management, unique feature/edition management and has a different usage in application. 
Users can only view space data that they are members of. So after registering in the application users are forced to subscribe to a space or create their own space. 
It's can be very useful for the companies with any scale of organizational. 
It's can be useful too for who want create single tenant intranet applications or social medias.

**Comment by hitaspdotnet** [comment]
```
-Application
--Tenant
---Organization Unit
----Articles
---Space
----Space Blogs //shared blogs in this space from members of this space who had write blog access
---User
----User Blogs  //shared blogs from this user in all spaces

```

**Comment by bbakermmc** [comment]
> Users can only view space data that they are members of. So after registering in the application users are forced to subscribe to a space or create their own space.

Making a user "subscribe" is bad.  If you use this in a corporate environment this would cause a whole bunch of headaches, HR makes posting, 99% of users not "subscribed" would cause nothing but issues :)

If talking about Blogs specifically, the ability to see them should be defined at Tenant, User, Feature, Permission, or OU level.  This would be useful for on boarding just like notifications.  We add new features to base code, all tenants can see a post about it.  We turn on a feature for a tenant the users who have the permission can see the how to use article.  We add a user to an OU they get to see the past things they have posted.

Once youre at the OU level, youre pretty specific, what youre talking about is basically "Topics/Subjects/Area"  You could create definable article types that allow for someone with correct permissions to set "Always view", or "User Defined View".  Then allow the users to "un check" topics that are "User Defined View" so they dont show up in their postings, b ut "Always View" is not uncheck-able.

**Comment by hitaspdotnet** [comment]
> Making a user "subscribe" is bad. If you use this in a corporate environment this would cause a whole bunch of headaches, HR makes posting, 99% of users not "subscribed" would cause nothing but issues :)

Hmmm,
In companies with large scale every department has own relations between their personals. I don't like to use tenant for each department BUT really want to use Feature management because in my case feature management is money maker🤣 . 
Turning off the tenant filter isn't good idea for +100/s requests on large DB. I had a try in my project with SPACE as top of tenants and OUs injected from SPACEs. But in debug with DB queries test i got ~400 request in the application with non data. They are only ABP's requests. 
I'm looking for a scenario to keeping Feature management for grouped users in single tenant and a way for easy relations between tenants.

**Comment by bbakermmc** [comment]
Having worked for employers like GE (300k+ employees) I can tell you that each department does not maintain their own relations.  There is a divisional level hierarchy.

IE:  You work at Site 1,  Site 1 is Part of Group 1, Group 1 is Part of segment A, Segment A falls under Division A,  Which is first child under corporate level GE.  Each level has their own report tos.  But if Segment A HR sends a message, it applies to EVERYONE under them.  I could also work at site 1, but my boss is actually at division A because certain groups IE IT/Finance tend to roll up to higher levels as they work cross segments, but my desk is at Site1, but it could be at Side 8 under Group3, Segment J if I lived closer to that one.

Your actual request seems no different that what I would want for Permission/Role/Feature management.
It has to be hierarchical.  I can set a feature at a tenant, role, user, or any OU hierarchical level.  Same for a role, a role can be a user, or OU hierarchical level, and Permissions are a User, Role, or OU Hierarchical level.

My actual use case above is something we have to deal with currently.  Our "Tenants" are "Clients" so our internal user access the Clients data thru the system, some clients have xyz feautre, and others have xyza feature.  I dont think you would ever setup a corp hierarchy via tenants, current version would be hard, maybe idea for new version, to allow nested tenants, then maybe what you want is viable for monetizing.
